export interface RaceData {
  sessionType: string;
  IsLimitedTime: boolean;
  isLimitedSessionLaps: boolean;
  currentLap: number;
  totalLaps: number;
  sessionTimeRemaining: number;
  position: number;
  speed: number;
  gear: string;
  rpm: number;
  rpmLights: { rpm: number; color: string }[];
  rpmMax: number;
  trackTemp: number;
  airTemp: number;
  fuelRemaining: number;
  fuelAvgLap: number;
  fuelLastLap: number;
  fuelEstLaps: number;
  brakeBias: number;
  strengthOfField: number;
  lastSectorNum: number;
  lastSectorTime: number;
  lastLapTime: number;
  lastLapTimeDelta: number;
  bestLapTime: number;
  bestLapTimeDelta: number;
  pitLimiterOn: boolean;
  incidents: number;
  maxIncidents: number;
  brakePct: number;
  throttlePct: number;
  carNumber: string;
}
