export { ClockComponent } from './clock/clock.component';
export { ConnectionStatusComponent } from './connection-status/connection-status.component';
export { DataElementComponent, DataType } from './data-element/data-element.component';
export { DataGroupComponent } from './data-group/data-group.component';
export { DeltaTimePipe } from './delta-time/delta-time.pipe';
export { LapTimePipe } from './laptime/laptime.pipe';
export { NumberFlexDigitPipe } from './number-flex-digit/number-flex-digit.pipe';
export { NumberNlPipe } from './number-nl/number-nl.pipe';
export { SpeedometerComponent } from './speedometer/speedometer.component';
export { TimespanPipe } from './timespan/timespan.pipe';
export { IRatingPipe } from './irating/irating.pipe';
export { GearPipe } from './gear/gear.pipe';
