export class RallyData {
  public speed = 0;
  public gear = 0;
  public rpm = 0;
  public maxRpm = 0;
  public distanceTravelled = 0;
  public completedPct = 0;
  public timeElapsed = 0;
  public sector1Time = 0;
  public sector2Time = 0;
  public lapTime = 0;
  public sector = 0;
  public position = 0;
  public brakeTempFl = 0;
  public brakeTempFr = 0;
  public brakeTempRl = 0;
  public brakeTempRr = 0;
  public tyrePressFl = 0;
  public tyrePressFr = 0;
  public tyrePressRl = 0;
  public tyrePressRr = 0;
}
