name: CI

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [main]

jobs:
 server-tests:
  name: Server tests
  runs-on: windows-latest

  env:
    solution_file: ./HaddySimHub.sln
    dotnet_version: '9.0.100'

  steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Cache NuGet packages
    uses: actions/cache@v3
    with:
      path: ~/.nuget/packages
      key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
      restore-keys: |
        nuget-${{ runner.os }}-

  - name: Install .NET Core
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: ${{ env.dotnet_version }}

  - name: Restore dependencies
    run: dotnet restore ${{ env.solution_file }}

  - name: Build
    run: dotnet build ${{ env.solution_file }} --no-restore

  - name: Test
    run: dotnet test ${{ env.solution_file }} --no-restore --no-build --verbosity normal

 clientapp-tests:
  name: Frontend tests
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./ClientApp/src
  env:
    node-version: 20

  steps:
    - uses: actions/checkout@v4

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('ClientApp/src/package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node-version }}

    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint

    - name: Run tests
      run: npm run test_ci

