name: CI

on:
  pull_request:
    branches: [main]

jobs:
 build:
    runs-on: windows-latest

    env:
      solution_file: ./src/HaddySimHub.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run:  dotnet restore $env:solution_file
    
    - name: Build
      run:  dotnet build $env:solution_file --no-restore
    
    - name: Test
      run:  dotnet test $env:solution_file --no-build
